# Neural-GPU Bus Docker Compose Configuration
# Revolutionary 3rd bus for hardware-accelerated compute coordination
version: '3.8'

services:
  neural-gpu-redis:
    image: redis:7-alpine
    container_name: nautilus-neural-gpu-bus
    restart: unless-stopped
    ports:
      - "6382:6379"  # Neural-GPU Bus port
    command: >
      redis-server 
      --maxmemory 8gb 
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 0
      --databases 16
      --save ""
      --appendonly no
      --tcp-backlog 511
      --maxclients 1000
      --loglevel notice
    volumes:
      - neural_gpu_redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
        reservations:
          cpus: '1.0'
          memory: 4G

volumes:
  neural_gpu_redis_data:
    driver: local

networks:
  default:
    name: nautilus_default