services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: nautilus-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8001
      - VITE_WS_URL=localhost:8001
    depends_on:
      - backend
    networks:
      - nautilus-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: nautilus-backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock:rw  # Docker socket access for dynamic container management
      - ./backend/engine_templates:/app/engine_templates:ro  # Engine configuration templates
      - ./backend/engine_bootstrap.py:/app/engine_bootstrap.py:ro
      - ./backend/nautilus_engine_runner.py:/app/nautilus_engine_runner.py:ro
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:80
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATABASE_URL=postgresql://nautilus:nautilus123@postgres:5432/nautilus
      # Dynamic Engine Container Configuration
      - DOCKER_ENGINE_MANAGEMENT=enabled
      - ENGINE_BASE_CONTAINER_NAME=nautilus-engine
      - ENGINE_DOCKER_IMAGE=nautilus-engine:latest
      - ENGINE_DOCKER_NETWORK=nautilus-network
      # IB Gateway Configuration
      - IB_HOST=host.docker.internal
      - IB_PORT=4002
      - TWS_ACCOUNT=DU7925702
      # YFinance Configuration (free public data)
      - YFINANCE_ENABLED=${YFINANCE_ENABLED:-true}
      - YFINANCE_RATE_LIMIT_DELAY=${YFINANCE_RATE_LIMIT_DELAY:-0.1}
      - YFINANCE_CACHE_EXPIRY_SECONDS=${YFINANCE_CACHE_EXPIRY_SECONDS:-3600}
      - YFINANCE_DEFAULT_PERIOD=${YFINANCE_DEFAULT_PERIOD:-1y}
      - YFINANCE_DEFAULT_INTERVAL=${YFINANCE_DEFAULT_INTERVAL:-1d}
      # Exchange API Configuration (set these for live trading)
      # Binance (defaults to testnet for safety)
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET:-}
      - BINANCE_SANDBOX=${BINANCE_SANDBOX:-true}
      - BINANCE_TRADING_MODE=${BINANCE_TRADING_MODE:-testnet}
      - BINANCE_BASE_URL=${BINANCE_BASE_URL:-https://testnet.binance.vision}
      - BINANCE_WS_URL=${BINANCE_WS_URL:-wss://testnet.binance.vision}
      # Coinbase (defaults to sandbox for safety)
      - COINBASE_API_KEY=${COINBASE_API_KEY:-}
      - COINBASE_API_SECRET=${COINBASE_API_SECRET:-}
      - COINBASE_PASSPHRASE=${COINBASE_PASSPHRASE:-}
      - COINBASE_SANDBOX=${COINBASE_SANDBOX:-true}
      - COINBASE_TRADING_MODE=${COINBASE_TRADING_MODE:-testnet}
      - COINBASE_BASE_URL=${COINBASE_BASE_URL:-https://api-public.sandbox.exchange.coinbase.com}
      # Bybit (defaults to testnet for safety)
      - BYBIT_API_KEY=${BYBIT_API_KEY:-}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET:-}
      - BYBIT_SANDBOX=${BYBIT_SANDBOX:-true}
      - BYBIT_TRADING_MODE=${BYBIT_TRADING_MODE:-testnet}
      - BYBIT_BASE_URL=${BYBIT_BASE_URL:-https://api-testnet.bybit.com}
      # Kraken (paper mode)
      - KRAKEN_API_KEY=${KRAKEN_API_KEY:-}
      - KRAKEN_API_SECRET=${KRAKEN_API_SECRET:-}
      - KRAKEN_TRADING_MODE=${KRAKEN_TRADING_MODE:-paper}
      # OKX (paper mode)
      - OKX_API_KEY=${OKX_API_KEY:-}
      - OKX_API_SECRET=${OKX_API_SECRET:-}
      - OKX_PASSPHRASE=${OKX_PASSPHRASE:-}
      - OKX_TRADING_MODE=${OKX_TRADING_MODE:-paper}
      # Data Source API Keys
      - FRED_API_KEY=1f1ba9c949e988e12796b7c1f6cce1bf
      - ALPHA_VANTAGE_API_KEY=271AHP91HVAPDRGP
    depends_on:
      - redis
      - postgres
    networks:
      - nautilus-network

  # Engine Template Container (for dynamic container creation)
  engine-template:
    build:
      context: ./backend
      dockerfile: Dockerfile.engine
    image: nautilus-engine:latest
    container_name: nautilus-engine-template
    # This container is built but not started - used as template for dynamic containers
    profiles: ["template"]
    volumes:
      - nautilus_engine_data:/app/data
      - nautilus_engine_cache:/app/cache
      - nautilus_engine_config:/app/config
      - nautilus_engine_results:/app/results
      - nautilus_engine_logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - NAUTILUS_ENGINE=true
      - RUST_BACKTRACE=1
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      # Engine-specific paths
      - NAUTILUS_DATA_PATH=/app/data
      - NAUTILUS_CACHE_PATH=/app/cache
      - NAUTILUS_CONFIG_PATH=/app/config
      - NAUTILUS_RESULTS_PATH=/app/results
      - NAUTILUS_LOG_PATH=/app/logs
      # Database connection
      - DATABASE_URL=postgresql://nautilus:nautilus123@postgres:5432/nautilus
      # Redis connection
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      # Trading configuration
      - TRADING_MODE=paper
      # IB Gateway Configuration
      - IB_HOST=host.docker.internal
      - IB_PORT=4002
      - TWS_ACCOUNT=DU7925702
    networks:
      - nautilus-network

  redis:
    image: redis:7-alpine
    container_name: nautilus-redis
    ports:
      - "6379:6379"
    networks:
      - nautilus-network

  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: nautilus-postgres
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
    environment:
      - POSTGRES_DB=nautilus
      - POSTGRES_USER=nautilus
      - POSTGRES_PASSWORD=nautilus123
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema/sql:/docker-entrypoint-initdb.d
    networks:
      - nautilus-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nautilus-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - nautilus-network

networks:
  nautilus-network:
    driver: bridge

volumes:
  node_modules:
  postgres_data:
  nautilus_engine_data:
  nautilus_engine_cache:
  nautilus_engine_config:
  nautilus_engine_results:
  nautilus_engine_logs: