# MarketData Bus - Neural Engine + Unified Memory Optimized
# Designed for high-throughput data distribution with aggressive caching

services:
  marketdata-redis-cluster:
    image: redis:7-alpine
    container_name: nautilus-marketdata-bus
    restart: unless-stopped
    environment:
      - REDIS_OPTIMIZATION_PROFILE=DATA_HEAVY
      - APPLE_SILICON_NEURAL_ENGINE=1
      - UNIFIED_MEMORY_POOL=64GB
      - CACHE_STRATEGY=AGGRESSIVE_LRU
      - REDIS_ARGS=--maxmemory 64gb --maxmemory-policy allkeys-lru --save 60 1000 --appendonly yes
    ports:
      - "6380:6379"  # Dedicated port for MarketData Bus
    volumes:
      - marketdata_cache_data:/data
      - ./config/redis-marketdata-fixed.conf:/usr/local/etc/redis/redis.conf:ro
    command: >
      redis-server /usr/local/etc/redis/redis.conf
      --port 6379
      --maxmemory 64gb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
      --tcp-keepalive 300
      --timeout 0
      --maxclients 10000
      --hz 10
    networks:
      - nautilus-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  marketdata_cache_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/marketdata_cache

networks:
  nautilus-network:
    external: true