# Prometheus Configuration for Nautilus Trading Platform
# Sprint 3: Advanced Trading Infrastructure Monitoring

global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  external_labels:
    monitor: 'nautilus-trading-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load alerting rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    
  # Nautilus Backend API
  - job_name: 'nautilus-backend'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Nautilus WebSocket metrics
  - job_name: 'nautilus-websocket'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 5s
    metrics_path: /ws/metrics
    
  # Trading Engine metrics
  - job_name: 'nautilus-engine'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 10s
    metrics_path: /api/v1/nautilus/engine/metrics
    
  # Performance Analytics metrics
  - job_name: 'nautilus-analytics'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 30s
    metrics_path: /api/v1/analytics/metrics
    
  # Risk Management metrics
  - job_name: 'nautilus-risk'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 10s
    metrics_path: /api/v1/risk/metrics
    
  # PostgreSQL metrics (if pg_exporter is available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Redis metrics (if redis_exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s
    
  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    
  # Application-specific custom metrics endpoints
  - job_name: 'nautilus-custom-metrics'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 15s
    metrics_path: /api/v1/monitoring/custom-metrics