# Enhanced Prometheus Configuration for M4 Max Optimized Nautilus Trading Platform
# Comprehensive monitoring for M4 Max hardware acceleration and container performance

global:
  scrape_interval: 5s # High frequency for trading systems
  evaluation_interval: 10s # Fast alert evaluation
  external_labels:
    monitor: 'nautilus-m4max-monitor'
    environment: 'production'
    chip: 'apple-m4-max'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Load alerting rules
rule_files:
  - "alert_rules.yml"
  - "m4max_alerts.yml"
  - "trading_alerts.yml"

# Enhanced scrape configuration for M4 Max optimization
scrape_configs:
  
  # ==============================================
  # CORE MONITORING INFRASTRUCTURE
  # ==============================================
  
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    
  # ==============================================
  # M4 MAX HARDWARE MONITORING
  # ==============================================
  
  # M4 Max Hardware Monitor
  - job_name: 'nautilus-m4max-hardware'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 5s # High frequency for hardware metrics
    metrics_path: '/api/v1/monitoring/m4max/hardware/metrics'
    scrape_timeout: 4s
    
  # M4 Max Neural Engine Monitor
  - job_name: 'nautilus-neural-engine'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 4s # High frequency for Neural Engine
    metrics_path: '/api/v1/monitoring/m4max/neural-engine/metrics'
    scrape_timeout: 3s
    
  # M4 Max GPU Monitor
  - job_name: 'nautilus-m4max-gpu'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 6s
    metrics_path: '/api/v1/monitoring/m4max/gpu/metrics'
    scrape_timeout: 5s
    
  # M4 Max Unified Memory Monitor
  - job_name: 'nautilus-unified-memory'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 4s # High frequency for memory monitoring
    metrics_path: '/api/v1/monitoring/m4max/memory/metrics'
    scrape_timeout: 3s
    
  # ==============================================
  # CONTAINER PERFORMANCE MONITORING
  # ==============================================
  
  # Container Performance Monitor
  - job_name: 'nautilus-containers'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 15s
    metrics_path: '/api/v1/monitoring/containers/metrics'
    scrape_timeout: 10s
    
  # cAdvisor for detailed container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Node exporter for system-level metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    
  # ==============================================
  # NAUTILUS TRADING ENGINES
  # ==============================================
  
  # Analytics Engine
  - job_name: 'nautilus-analytics-engine'
    static_configs:
      - targets: ['nautilus-analytics-engine:8100']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Risk Engine
  - job_name: 'nautilus-risk-engine'
    static_configs:
      - targets: ['nautilus-risk-engine:8200']
    scrape_interval: 3s # High frequency for risk monitoring
    metrics_path: /metrics
    
  # Factor Engine
  - job_name: 'nautilus-factor-engine'
    static_configs:
      - targets: ['nautilus-factor-engine:8300']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # ML Engine
  - job_name: 'nautilus-ml-engine'
    static_configs:
      - targets: ['nautilus-ml-engine:8400']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Features Engine
  - job_name: 'nautilus-features-engine'
    static_configs:
      - targets: ['nautilus-features-engine:8500']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # WebSocket Engine
  - job_name: 'nautilus-websocket-engine'
    static_configs:
      - targets: ['nautilus-websocket-engine:8600']
    scrape_interval: 3s # High frequency for real-time data
    metrics_path: /metrics
    
  # Strategy Engine
  - job_name: 'nautilus-strategy-engine'
    static_configs:
      - targets: ['nautilus-strategy-engine:8700']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Market Data Engine
  - job_name: 'nautilus-marketdata-engine'
    static_configs:
      - targets: ['nautilus-marketdata-engine:8800']
    scrape_interval: 2s # High frequency for market data
    metrics_path: /metrics
    
  # Portfolio Engine
  - job_name: 'nautilus-portfolio-engine'
    static_configs:
      - targets: ['nautilus-portfolio-engine:8900']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # ==============================================
  # ENGINE MESSAGEBUS & CLOCK OPTIMIZATION
  # ==============================================
  
  # Analytics Engine MessageBus Performance
  - job_name: 'nautilus-analytics-messagebus'
    static_configs:
      - targets: ['nautilus-analytics-engine:8100']
    scrape_interval: 3s
    metrics_path: /messagebus/metrics
    scrape_timeout: 2s
    
  # Risk Engine Clock Optimization (Simulated clock implementation)
  - job_name: 'nautilus-risk-clock'
    static_configs:
      - targets: ['nautilus-risk-engine:8200']
    scrape_interval: 5s
    metrics_path: /clock/metrics
    scrape_timeout: 4s
    
  # ML Engine MessageBus Performance
  - job_name: 'nautilus-ml-messagebus'
    static_configs:
      - targets: ['nautilus-ml-engine:8400']
    scrape_interval: 3s
    metrics_path: /messagebus/metrics
    scrape_timeout: 2s
    
  # Factor Engine Clock Synchronization
  - job_name: 'nautilus-factor-clock'
    static_configs:
      - targets: ['nautilus-factor-engine:8300']
    scrape_interval: 10s
    metrics_path: /clock/metrics
    scrape_timeout: 8s
    
  # WebSocket Engine MessageBus (Real-time streaming)
  - job_name: 'nautilus-websocket-messagebus'
    static_configs:
      - targets: ['nautilus-websocket-engine:8600']
    scrape_interval: 2s # Very high frequency for real-time
    metrics_path: /messagebus/metrics
    scrape_timeout: 1s
    
  # ==============================================
  # CORE APPLICATION SERVICES
  # ==============================================
  
  # Backend API
  - job_name: 'nautilus-backend'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Trading Performance Monitor
  - job_name: 'nautilus-trading-performance'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 20s
    metrics_path: '/api/v1/monitoring/trading/metrics'
    scrape_timeout: 15s
    
  # WebSocket Infrastructure
  - job_name: 'nautilus-websocket'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 3s
    metrics_path: /ws/metrics
    
  # ==============================================
  # DATABASE AND CACHE MONITORING
  # ==============================================
  
  # PostgreSQL with TimescaleDB
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    scrape_timeout: 10s
    
  # Redis Cache and Pub/Sub
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    
  # ==============================================
  # SPECIALIZED M4 MAX OPTIMIZATIONS
  # ==============================================
  
  # M4 Max CPU Optimization Monitor
  - job_name: 'nautilus-cpu-optimization'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 4s
    metrics_path: '/api/v1/monitoring/m4max/cpu-optimization/metrics'
    scrape_timeout: 3s
    
  # M4 Max Memory Pool Monitor
  - job_name: 'nautilus-memory-pools'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 6s
    metrics_path: '/api/v1/monitoring/m4max/memory-pools/metrics'
    scrape_timeout: 5s
    
  # M4 Max GPU Acceleration Monitor
  - job_name: 'nautilus-gpu-acceleration'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 4s
    metrics_path: '/api/v1/monitoring/m4max/gpu-acceleration/metrics'
    scrape_timeout: 3s
    
  # Enhanced MessageBus Performance Monitor (10x improvement tracking)
  - job_name: 'nautilus-messagebus-optimization'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 2s # High frequency for real-time messaging
    metrics_path: '/api/v1/monitoring/messagebus/performance/metrics'
    scrape_timeout: 1s
    
  # Clock Optimization Monitor (Simulated clock for deterministic testing)
  - job_name: 'nautilus-clock-optimization'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 5s
    metrics_path: '/api/v1/monitoring/clock/optimization/metrics'
    scrape_timeout: 4s
    
  # MessageBus Redis Pub/Sub Performance
  - job_name: 'nautilus-messagebus-redis'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 3s
    metrics_path: '/api/v1/monitoring/messagebus/redis/metrics'
    scrape_timeout: 2s
    
  # Inter-Engine Communication Monitor
  - job_name: 'nautilus-inter-engine-communication'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 5s
    metrics_path: '/api/v1/monitoring/engines/communication/metrics'
    scrape_timeout: 4s
    
  # ==============================================
  # EXTERNAL DATA SOURCES
  # ==============================================
  
  # Data Source Performance
  - job_name: 'nautilus-data-sources'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 30s
    metrics_path: '/api/v1/monitoring/data-sources/metrics'
    scrape_timeout: 15s
    
  # ==============================================
  # BUSINESS METRICS
  # ==============================================
  
  # Trading Metrics
  - job_name: 'nautilus-trading-metrics'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 15s
    metrics_path: '/api/v1/analytics/trading-metrics'
    scrape_timeout: 10s
    
  # Risk Management Metrics
  - job_name: 'nautilus-risk-metrics'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 6s # High frequency for risk
    metrics_path: '/api/v1/risk/metrics'
    scrape_timeout: 5s
    
  # Portfolio Performance
  - job_name: 'nautilus-portfolio-metrics'
    static_configs:
      - targets: ['nautilus-backend:8000']
    scrape_interval: 10s
    metrics_path: '/api/v1/portfolio/metrics'
    scrape_timeout: 10s
    
  # ==============================================
  # MONITORING INFRASTRUCTURE
  # ==============================================
  
  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['nautilus-grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

# Note: Storage and query parameters are configured via command-line flags
# in docker-compose.yml for M4 Max optimization:
# --storage.tsdb.path=/prometheus
# --storage.tsdb.retention.time=30d
# --storage.tsdb.retention.size=50GB 
# --storage.tsdb.wal-compression=true
# --query.timeout=30s
# --query.max-concurrency=20