apiVersion: v1
kind: Namespace
metadata:
  annotations:
    istio-injection: enabled
  labels:
    federation: nautilus-global
    name: nautilus-federation
    tier: multi-cloud
  name: nautilus-federation
