apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nautilus-global-gateway
  namespace: nautilus-federation
spec:
  selector:
    istio: eastwestgateway
  servers:
  - hosts:
    - '*.nautilus.local'
    port:
      name: tls
      number: 443
      protocol: TLS
    tls:
      mode: ISTIO_MUTUAL
