---
# PostgreSQL Primary Headless Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql-primary-headless
  namespace: nautilus-trading
  labels:
    app.kubernetes.io/name: postgresql-primary
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nautilus-trading
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql-primary
    role: primary

---
# PostgreSQL Primary Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql-primary
  namespace: nautilus-trading
  labels:
    app.kubernetes.io/name: postgresql-primary
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nautilus-trading
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql-primary
    role: primary
  type: LoadBalancer

---
# PostgreSQL Replica Headless Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql-replica-headless
  namespace: nautilus-trading
  labels:
    app.kubernetes.io/name: postgresql-replica
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nautilus-trading
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql-replica
    role: replica

---
# PostgreSQL Replica Service (Read-only load balancer)
apiVersion: v1
kind: Service
metadata:
  name: postgresql-replica
  namespace: nautilus-trading
  labels:
    app.kubernetes.io/name: postgresql-replica
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nautilus-trading
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql-replica
    role: replica
  type: LoadBalancer
  sessionAffinity: None

---
# PostgreSQL Combined Service (Smart routing via PgBouncer)
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: nautilus-trading
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database-proxy
    app.kubernetes.io/part-of: nautilus-trading
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
    protocol: TCP
  selector:
    app.kubernetes.io/name: pgbouncer
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300

---
# PostgreSQL Backup Service (for backup operations)
apiVersion: v1
kind: Service
metadata:
  name: postgresql-backup
  namespace: nautilus-trading
  labels:
    app.kubernetes.io/name: postgresql-backup
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: nautilus-trading
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql-primary
    role: primary
  type: ClusterIP

---
# PostgreSQL Monitoring Service (for monitoring tools)
apiVersion: v1
kind: Service
metadata:
  name: postgresql-monitoring
  namespace: nautilus-trading
  labels:
    app.kubernetes.io/name: postgresql-monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: nautilus-trading
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql-primary
    role: primary
  type: ClusterIP

---
# PostgreSQL Endpoints for external monitoring
apiVersion: v1
kind: Endpoints
metadata:
  name: postgresql-external-monitor
  namespace: nautilus-trading
  labels:
    app.kubernetes.io/name: postgresql-external-monitor
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: nautilus-trading
subsets:
- addresses:
  - ip: "postgresql-primary.nautilus-trading.svc.cluster.local"
  - ip: "postgresql-replica.nautilus-trading.svc.cluster.local"
  ports:
  - port: 5432
    name: postgres