apiVersion: v1
kind: Service
metadata:
  name: nautilus-integration-engine
  namespace: nautilus-trading
  labels:
    app: nautilus-integration-engine
    tier: ultra-low-latency
    version: phase4
    component: integration-coordinator
  annotations:
    service.kubernetes.io/load-balancer-class: "internal"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: LoadBalancer  # External access for trading operations
  selector:
    app: nautilus-integration-engine
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: metrics  
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: 8080
    protocol: TCP
  # Load balancer configuration for high availability
  externalTrafficPolicy: Local  # Preserve client IP for better routing